-- Create and grant a schema for the project (edit the password!)
-- RUN AS: SYSTEM or SYS AS SYSDBA, connected to XEPDB1
CREATE USER EWULIB IDENTIFIED BY "CHANGE_ME_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO EWULIB;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO EWULIB;
