-- Run in schema EWULIB
CREATE TABLE member (
  member_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name      VARCHAR2(120) NOT NULL,
  email          VARCHAR2(120) UNIQUE,
  dept           VARCHAR2(80),
  member_type    VARCHAR2(20) CHECK (member_type IN ('Student','Faculty','Staff'))
);

CREATE TABLE staff (
  staff_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR2(120) NOT NULL,
  role_title  VARCHAR2(80)
);

CREATE TABLE category (
  category_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(80) UNIQUE
);

CREATE TABLE author (
  author_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(120) NOT NULL
);

CREATE TABLE book (
  book_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  isbn              VARCHAR2(20) UNIQUE,
  title             VARCHAR2(200) NOT NULL,
  publisher         VARCHAR2(120),
  publish_year      NUMBER(4),
  category_id       NUMBER REFERENCES category(category_id),
  total_copies      NUMBER DEFAULT 1 CHECK (total_copies >= 0),
  available_copies  NUMBER DEFAULT 1 CHECK (available_copies >= 0)
);

CREATE TABLE book_author (
  book_id    NUMBER REFERENCES book(book_id),
  author_id  NUMBER REFERENCES author(author_id),
  CONSTRAINT pk_book_author PRIMARY KEY (book_id, author_id)
);

CREATE TABLE borrow_txn (
  txn_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    NUMBER REFERENCES member(member_id),
  book_id      NUMBER REFERENCES book(book_id),
  borrowed_on  DATE DEFAULT SYSDATE NOT NULL,
  due_on       DATE NOT NULL,
  returned_on  DATE
);
